services:	
 mongodbsp:
  image: mongo
  container_name: mongo_db
  ports:
   - 27017:27017
  volumes:
   - mongo:/data
  environment:
   - MONGO_INITDB_ROOT_USERNAME=spatidar
   - MONGO_INITDB_ROOT_PASSWORD=spatidar
 mongo-express:
  image: mongo-express
  container_name: mongo_express
  ports:
   - 8081:8081
  environment:
   - ME_CONFIG_MONGODB_ADMINUSERNAME=spatidar
   - ME_CONFIG_MONGODB_ADMINPASSWORD=spatidar
   - ME_CONFIG_MONGODB_SERVER=mongodbsp	
volumes:
 mongo: {}